name: Build Windows Application

on:
  release:
    types: [created]

jobs:
  build-windows:
    runs-on: windows-latest
    
    permissions:
      contents: write

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install customtkinter yt-dlp pyinstaller Pillow
        shell: pwsh

      - name: Download FFmpeg
        run: |
          Invoke-WebRequest -Uri https://github.com/BtbN/FFmpeg-Builds/releases/download/latest/ffmpeg-master-latest-win64-gpl.zip -OutFile ffmpeg.zip
          Expand-Archive ffmpeg.zip -DestinationPath ffmpeg
        shell: pwsh

      - name: Build the application
        run: |
          pyinstaller --noconsole --onedir --windowed --name "Universal Media Downloader" `
            --icon="GUI_Downloader/icon.ico" `
            --add-binary "ffmpeg/ffmpeg-master-latest-win64-gpl/bin/ffmpeg.exe;." `
            --add-binary "ffmpeg/ffmpeg-master-latest-win64-gpl/bin/ffprobe.exe;." `
            "GUI_Downloader/Universal Media Downloader.py"
        shell: pwsh

      - name: Zip the output folder
        run: |
          cd dist
          Compress-Archive -Path "Universal Media Downloader" -DestinationPath ../Universal-Media-Downloader-Windows.zip
        shell: pwsh

      - name: Upload Release Asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./Universal-Media-Downloader-Windows.zip
          asset_name: Universal-Media-Downloader-Windows.zip
          asset_content_type: application/zip
