name: Build Windows Application

on:
  release:
    types: [created]

jobs:
  build-windows:
    runs-on: windows-latest

    permissions:
      contents: write

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies and ffmpeg
        run: |
          python -m pip install --upgrade pip
          pip install customtkinter yt-dlp pyinstaller Pillow
          choco install ffmpeg -y

      - name: Locate ffmpeg and ffprobe paths
        id: locate_ffmpeg
        shell: pwsh
        run: |
          $ffmpegPath = (where.exe ffmpeg | Select-Object -First 1).Trim()
          $ffprobePath = (where.exe ffprobe | Select-Object -First 1).Trim()
          if (-not (Test-Path $ffmpegPath)) {
            Write-Error "ffmpeg not found in PATH"
            exit 1
          }
          if (-not (Test-Path $ffprobePath)) {
            Write-Error "ffprobe not found in PATH"
            exit 1
          }
          Write-Host "ffmpeg path: $ffmpegPath"
          Write-Host "ffprobe path: $ffprobePath"
          echo "ffmpeg=$ffmpegPath" >> $env:GITHUB_OUTPUT
          echo "ffprobe=$ffprobePath" >> $env:GITHUB_OUTPUT

      - name: Clean previous builds
        run: |
          Remove-Item -Recurse -Force .\build, .\dist

      - name: Build the application
        run: |
          pyinstaller --clean --noconsole --onedir --windowed --name "Universal Media Downloader" `
            --icon="GUI_Downloader\icon.ico" `
            --add-binary "${{ steps.locate_ffmpeg.outputs.ffmpeg }};." `
            --add-binary "${{ steps.locate_ffmpeg.outputs.ffprobe }};." `
            "GUI_Downloader\Universal Media Downloader.py"

      - name: Zip the output folder
        run: |
          powershell Compress-Archive -Path '.\dist\Universal Media Downloader\*' -DestinationPath '.\dist\Universal-Media-Downloader-Windows.zip'

      - name: Upload Release Asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./dist/Universal-Media-Downloader-Windows.zip
          asset_name: Universal-Media-Downloader-Windows.zip
          asset_content_type: application/zip
