name: Build Windows Application

on:
  release:
    types: [created]

jobs:
  build-windows:
    runs-on: windows-latest
    
    permissions:
      contents: write

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install customtkinter yt-dlp pyinstaller Pillow

      - name: Build the application
        run: |
          pyinstaller --noconsole --onedir --windowed --name "Universal Media Downloader" \
            --icon="GUI_Downloader\\icon.ico" \
            --add-binary "GUI_Downloader\\ffmpeg.exe;." \
            --add-binary "GUI_Downloader\\ffprobe.exe;." \
            "GUI_Downloader\\Universal Media Downloader.py"

      - name: Zip the output folder
        run: |
          powershell Compress-Archive -Path .\dist\Universal\ Media\ Downloader\* -DestinationPath .\dist\Universal-Media-Downloader-Windows.zip

      - name: Upload Release Asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./dist/Universal-Media-Downloader-Windows.zip
          asset_name: Universal-Media-Downloader-Windows.zip
          asset_content_type: application/zip
