# .github/workflows/build-windows.yml

name: Build Windows Application

on:
  release:
    types: [created]

jobs:
  build-windows:
    runs-on: windows-latest

    permissions:
      contents: write

    steps:
      # Step 1: Check out your repository's code
      - name: Check out code
        uses: actions/checkout@v3

      # Step 2: Set up Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      # Step 3: Install dependencies and ffmpeg
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install customtkinter yt-dlp pyinstaller Pillow
          choco install ffmpeg -y

      # Step 4: Build the application with PyInstaller
      - name: Build the application
        shell: pwsh
        run: |
          pyinstaller --noconsole --onedir --windowed --name "Universal Media Downloader" `
            --icon "GUI_Downloader\icon.ico" `
            --add-binary ((Get-Command ffmpeg.exe).Source + ";.") `
            --add-binary ((Get-Command ffprobe.exe).Source + ";.") `
            "GUI_Downloader\Universal Media Downloader.py"

      # Step 5: Zip the output folder for release (FIXED)
      - name: Zip the output folder
        shell: pwsh
        run: |
          cd dist
          Compress-Archive -Path '.\Universal Media Downloader' -DestinationPath '..\Universal-Media-Downloader-Windows.zip'
        
      # Step 6: Upload the zip file as a release asset
      - name: Upload Release Asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./Universal-Media-Downloader-Windows.zip
          asset_name: Universal-Media-Downloader-Windows.zip
          asset_content_type: application/zip